### ISSUE TITLE
Linux Only?

### ISSUE THREAD

**Issue by LuoZijun** [polachok/pnetlink#34]

**Comment by bkchr** [comment]
What OS do you need?

**Comment by LuoZijun** [comment]
humm,  bsd-like (macos, freebsd, netbsd) and windows ?

i think this project very like [borkmann/iproute2](https://github.com/borkmann/iproute2) .

i'm very interesting on that.

and i havn't see an license.

**Comment by LuoZijun** [comment]
the `example/ip_link.rs` i has impl already with `libpnet` , wait to merge.

https://github.com/LuoZijun/libpnet/blob/patch-1/pnet_datalink/src/lib.rs#L234

https://github.com/LuoZijun/libpnet/blob/patch-1/examples/list_interfaces.rs

**Comment by bkchr** [comment]
Could you provide patches for BSD systems? I don't know if they support netlink. But I don't think that windows supports that.

**Comment by LuoZijun** [comment]
of course, next week.

**Comment by polachok** [comment]
Netlink sockets are not supported on BSDs as far as I know.

**Comment by LuoZijun** [comment]
@polachok you are right.

@bkchr 
the `pnet` project just impl `ip addr`.

i just has read this project code, 
now i know this project use linux `netlink` api to get `ip address/ip neighbor/ip route` info.

point is use `netlink` api.

sorry for wasting your time.
