### ISSUE TITLE
Parse complete frame

### ISSUE THREAD

**Issue by Yamakaky** [polachok/pnetlink#7]
For now, we have only things like "bytes -> Ethernet", where the payload is not decoded. It would be cool to be able to decode an Ethernet frame and automatically have the ip and tcp layers decoded.

**Comment by polachok** [comment]
I think you're in the wrong repository for this :) This is a library for netlink protocol (used by linux `ip` family of tools).

**Comment by Yamakaky** [comment]
Oops, sorry. I was looking for libpnet ^^
